---
abstract: 'Classes for building a Router (Standford) style CLI'
author:
  - 'Bret Jordan'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-RouterCLI
no_index:
  directory:
    - t
    - inc
requires:
  Config::General: 2.5
  Digest::SHA: 5.62
  Env: 1
  FileHandle: 2.02
  POSIX: 1.17
  Sys::Syslog: 0.29
  Term::ReadKey: 2.3
  Term::ReadLine::Gnu: 1.2
  Test::More: 0.98
  Test::Output: 1.01
  Text::Shellwords::Cursor: 0.81
  parent: 0.221
version: 0.99_13
